In [ ]:
# Print your name, age city using f-string
name = input("Enter your name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")

print(f"Your name is {name}, Age: {age} and you live in {city}")

In [ ]:
# Take input of 2 numbers and compare the values

x = int(input("Enter the first number: "))
y = int(input("Enter the second number: "))

if x>y:
  print (f"{x} is greater than {y}")
elif x<y:
  print (f"{x} is less than {y}")
else:
  print (f"{x} is equal to {y}")

Enter the first number: 15
Enter the second number: 20
15 is less than 20


In [ ]:
list_1 = [1, 2, 3]
list_2 = [1, 2, 3]
print(type(list_1))
print(list_1 == list_2)
print (list_1 is list_2)


<class 'list'>
True
False


In [ ]:
# Area of circle

r = int(input("Enter the radius: "))
print("Area of circle is: ", 3.14*r*r)

Enter the radius: 5
Area of circle is:  78.5


In [ ]:
# Check if the number is even or odd

a = int(input("Enter a number to check if it is even or odd: "))
if a % 2 == 0:
  print("The number is even")
else:
  print("The number is odd")

Enter a number to check if it is even or odd: 5
The number is odd


In [ ]:
# Calculate the total and avg of 3 subjects marks

sub1 = int(input("Enter the marks of subject 1: "))
sub2 = int(input("Enter the marks of subject 2: "))
sub3 = int(input("Enter the marks of subject 3: "))

total = sub1 + sub2 + sub3
avg = total / 3

print("Total marks: ", total)
print("Average marks: ", avg)

Enter the marks of subject 1: 20
Enter the marks of subject 2: 22
Enter the marks of subject 3: 18
Total marks:  60
Average marks:  20.0


In [ ]:
# Password Check Program

password = "Aastha"

enter_pass = input("Enter the password: ")

if enter_pass == password:
  print("Password is correct")
else:
  print("Password is incorrect")

Enter the password: Aastha
Password is correct


In [ ]:
# List - Mutable
# listone = [1, 2 , 3, "Aastha"]
# print(listone)
# print(listone[0])
# print(listone[2])

# Tuple
# tup = (1, 2, 3, 4, "Aastha")
# print(tup)
# print(type(tup))

# Dictonary
# details = {
#     "name":"Aastha",
#     "age":20,
#     "city":"Jaipur"
# }
# print(details)
# print(details["name"])
# print(details["age"])
# print(details["city"])




[1, 2, 3, 'Aastha']
(1, 2, 3, 4, 'Aastha')
<class 'tuple'>


In [ ]:

my_cart = ["Milk", "Butter", "Bread"]

# print(type(my_cart))

# print(my_cart[0])

# print(my_cart)
# my_cart.append("Sugar")
# print(my_cart)
# my_cart.remove("Milk")

print(my_cart)

my_cart[:-2] = "Teal"
print(my_cart)

my_cart[:-1] = "Hot milk"
print(my_cart)


['Milk', 'Butter', 'Bread']
['T', 'e', 'a', 'l', 'Butter', 'Bread']
['H', 'o', 't', ' ', 'm', 'i', 'l', 'k', 'Bread']


In [ ]:
stud_details = [
    {
        'name': 'Aastha',
        'roll_number': 1,
        'phone_numbers': ['123', '456']
    },
    {
        'name': 'Aishwarya',
        'roll_number': 2,
        'phone_numbers': ['789', '101112']
    },
    {
        'name': 'Tanushree',
        'roll_number': 3,
        'phone_numbers': ['1314', '1516']
    }
]


print(f"First student's name: {stud_details[1]['name']}")
print(f"First student's primary phone: {stud_details[0]['phone_numbers']}")


for student in stud_details:
    print(f"Name: {student['name']}, Roll Number: {student['roll_number']}, Phone No.: {student['phone_numbers']}")

First student's name: Aishwarya
First student's primary phone: ['123', '456']
Name: Aastha, Roll Number: 1, Phone No.: ['123', '456']
Name: Aishwarya, Roll Number: 2, Phone No.: ['789', '101112']
Name: Tanushree, Roll Number: 3, Phone No.: ['1314', '1516']


In [ ]:
# Loops for printing the table
a = int(input("Enter the number for knowing the tables: "))
i = 1

while (i<=10):
  print(f"{a} X {i}: {a*i}")
  i+=1


Enter the number for knowing the tables: 3
3 X 1: 3
3 X 2: 6
3 X 3: 9
3 X 4: 12
3 X 5: 15
3 X 6: 18
3 X 7: 21
3 X 8: 24
3 X 9: 27
3 X 10: 30


In [ ]:
# printing total sum from 0 to 100

total=0
num = 1

while (num <=100):
  total = total + num
  num =num + 1

print(total)

5050


In [ ]:
# Reverse num using while loop

num = 123
print(num)

rev_num = 0
while number > 0:
    digit = number % 10  # Get the last digit
    rev_num = rev_num * 10 + digit  # Append the digit to the reversed number
    number = number // 10  # Remove the last digit from the original number


In [ ]:
## numpy - 24/9

import numpy as np
import random

# random.seed(1)
# print(random.random())

#Array
# x = np.array(6)

# Vector
# x = np.array([1.3 , 2.2 , 1.7])

# Matrix
# x = np.array(
#     [[1,2],
#      [3,4]]
#     )

# 3-D Tensor - storing Multiple matrices
x = np.array(
    [[[1,2],
     [3,4]],
     [[5,6],
      [7,8]]]
    )


print("x:", x)
print("The dimension of x is:", x.ndim)
print("The shape of x is:", x.shape)
print("The size of x is:", x.size)
print("The data type of x is:", x.dtype)

x: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
The dimension of x is: 3
The shape of x is: (2, 2, 2)
The size of x is: 8
The data type of x is: int64


In [ ]:
import numpy as np
import random

x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
print(x)
print("x coloum 1:", x[:,0])
print("x row 0:", x[0,:])
print("x:", x[0:2,1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x coloum 1: [1 5 9]
x row 0: [1 2 3 4]
x: [[2 3]
 [6 7]]


In [7]:
def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)

Python is fantastic
Python is awesome
